### ISSUE TITLE
RoadMap Section

### ISSUE THREAD

**Issue by marcdhi** [WebClub-NITK/wec-nitk-website#20]
Need a page where all SIGs can create a general path on how to sort of reach the level required to get into web club -> Add resources for the path -> Add assignments (try to make the roadmap calculation in terms of weeks)

**Comment by Shubham-Rasal** [comment]
Any particular structure? or need to discuss in the core first?

**Comment by marcdhi** [comment]
> Any particular structure? or need to discuss in the core first?

Yeah let's discuss on the core first.
