### ISSUE TITLE
Events section 

### ISSUE THREAD

**Issue by ahmedfahim21** [WebClub-NITK/wec-nitk-website#5]
- [ ] List all events:
> Section in Home Page where few recent events would displayed in cards.
> `See All` button would take you to a Events page.
- [ ] Event modal
> would contain info like :   title, date, content, sig, cover image, location, link if Online/Hybrid, CEMS link, resources.

**Comment by AahilRafiq** [comment]
Regarding the colors , are we using colors only from the color palette ? , coz for the dark theme we need more color ?
