### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by ahmedfahim21** [WebClub-NITK/wec-nitk-website#6]
Display all members, SIG wise filters, alumni.
A member card would have the following info : picture, name, role/position, SIG, github link, linkedIn link, mail id, twitter link.

**Comment by Cioraz** [comment]
Right are we trying to use something like the current layout  or going ahead with a total revamp?
![Screenshot from 2024-02-19 19-16-05](https://github.com/WebClub-NITK/wec-nitk-website/assets/76161837/c98ce141-9e05-4909-b13e-be71b57c4f3c)

**Comment by ahmedfahim21** [comment]
> Right are we trying to use something like the current layout or going ahead with a total revamp? I see that the card has way more details than the current but apart from that the overall layout and structure will be the same?

Yes, structure as in the filters will be there, and the individual card. 
But obviously we need significant UI improvement, hover effects etc.

You can search and share some possible design inspirations from other websites/component-library, here. We can then decide which to select and proceed.

**Comment by Cioraz** [comment]
Sorry for the delayed response but came across meterial ui which I thought has a good fit seems also to have nextjs support. Any advice?

**Comment by Shubham-Rasal** [comment]
You can choose any component library. Material UI is also fine, just ensure whatever you choose should be inline with the theme. You can have a look at shadcn, https://ui.aceternity.com/components, hover.dev.
