### ISSUE TITLE
Blogs page

### ISSUE THREAD

**Issue by ahmedfahim21** [WebClub-NITK/wec-nitk-website#7]
- [x] List all blogs:
>  displayed info like : title, subheading, tags, written on (date), written by, cover picture.
- [x] Blog page
>  a blog would contain info like :  title, subheading, written on (date), written by, cover picture, content.
> Content would be in markdown, so use react-markdown to display content in the expected format.

**Comment by Shubham-Rasal** [comment]
What would be the best way for people to write blogs for the site?

My plan was to set up the workflow in GitHub and write the blog as a PR which when merged will be updated in the appropriate table in strapi 

We can create an issue template for blogs.
